version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 myflights.wsgi
    volumes:
      - '.:/usr/src/app'
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5438:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
