version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/usr/src/app'
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5436:5432
