# Generated by Django 2.2.5 on 2019-09-30 12:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Airline name')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Airline alias')),
                ('iata', models.CharField(blank=True, max_length=3, null=True, verbose_name='3-letter IATA code')),
                ('icao', models.CharField(blank=True, max_length=4, null=True, verbose_name='4-letter ICAO code')),
                ('callsign', models.CharField(blank=True, max_length=50, null=True, verbose_name='Airline callsign')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country or territory where Airline is incorporated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Airline operational or defunct')),
                ('openflights_id', models.IntegerField(blank=True, null=True, verbose_name='ID from OpenFlights database')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Airport name')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='City name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('iata', models.CharField(blank=True, max_length=3, null=True, verbose_name='3-letter IATA code')),
                ('icao', models.CharField(blank=True, max_length=4, null=True, verbose_name='4-letter ICAO code')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (meters)')),
                ('timezone_offset', models.FloatField(blank=True, null=True, verbose_name='Offset from UTC in hours')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time zone name in tz (Olsom) format')),
                ('openflights_id', models.IntegerField(blank=True, null=True, verbose_name='ID from OpenFlights database')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stops', models.IntegerField(blank=True, null=True, verbose_name='Number of stops on route')),
                ('equipment', models.CharField(max_length=100, verbose_name='3-letter codes for plane type')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.Airline', verbose_name='Airline that operates the route')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='core.Airport', verbose_name='Destination Airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='core.Airport', verbose_name='Origin Airport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateTimeField(verbose_name='Departure date time in UTC')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival date time in UTC')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='core.Route', verbose_name='Route of the flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
